name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
  workflow_dispatch:

permissions:
  contents: read



jobs:

  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: erlang:latest
    steps:
    - uses: actions/checkout@v3
    - name: Compile
      run: rebar3 compile
    - name: Run tests
      run: rebar3 do eunit, cover

  codecov:
    runs-on: ubuntu-latest
    container:
      image: erlang:latest
    steps:
    - name: convert-t-json
      run: rebar3 codecov analyze path="_build/test/cover"
    - uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV }}
        files: ./codecov.json
        verbose: true
